# Website settings
url: "https://dn00.github.io"

# Internal nav
nav:
  main:
    # writing: "/writing"
    # speaking: "/speaking"
    projects: "/projects"
    # photos: "/photos"
  # writing:
  #   all: "/writing"
  #   popular: "/writing/popular"
  #   tags: "/writing/tags"
  #   rss: "/feed.xml"

# Bio settings
name: "Dennis Tin Nguyen"
description: "The home page of Dennis Tin Nguyen."
thumbnail_path: "profile-photos/dtnguy-medium.jpg"
bitcoin_address: ""
hello_startup_url: ""
website_repo_url: "https://github.com/dn00/dn00.github.io"
atomic_squirrel_url: ""
gruntwork_url: ""
terraform_up_and_running_url: ""
terraform_up_and_running_code_url: ""

# URLs
contact_urls:
  # twitter:
  #   url: "https://twitter.com/brikis98"
  #   label: "Twitter"
  #   icon: "twitter-square"
  #   username: "@brikis98"
  # linkedin:
  #   url: "https://www.linkedin.com/in/jbrikman"
  #   label: "LinkedIn"
  #   icon: "linkedin-square"
  # facebook:
  #   url: "https://www.facebook.com/dtn00"
  #   label: "Facebook"
  #   icon: "facebook-square"
  # google:
  #   url: "https://plus.google.com/+YevgeniyBrikman/"
  #   label: "Google+"
  #   icon: "google-plus-square"
  # slideshare:
  #   url: "https://www.slideshare.net/brikis98"
  #   label: "SlideShare"
  #   icon: "slideshare"
  github:
    url: "https://github.com/dn00/"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:dtnguy90@gmail.com"
    label: "Email"
    value: "dtnguy90@gmail.com"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'
repository: dn00/dn00.github.io

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
